# Generated by Django 3.1.7 on 2021-03-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210325_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
