# Generated by Django 3.1.7 on 2021-03-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staffprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
