# Generated by Django 3.1.7 on 2022-07-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210405_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'verbose_name': 'Employee Profile', 'verbose_name_plural': 'Employee Profile'},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'Donor Profile', 'verbose_name_plural': 'Donor Profile'},
        ),
    ]
