# Generated by Django 3.1.7 on 2021-04-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age_of_heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='blood_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='blood_sodium_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='blood_sugar_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='body_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='current_medical_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='mri_scan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='other_diagonosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='previous_medical_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='xray',
            field=models.BooleanField(default=False),
        ),
    ]
