# Generated by Django 3.1.7 on 2022-07-06 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220707_0036'),
        ('age_of_heroes', '0002_auto_20210409_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_report_patient', to='accounts.patientprofile'),
        ),
    ]
